/* FAQ accordion — renders collapsible <details> entries */
(() => {
  const FAQ = [
    ["Q.01", "What is Pixton?",
      "Pixton is a tiny, observable town. Six residents live inside it on a 2-second clock — they wander the square, bump into each other, and exchange small lines that come from a generative model. The town keeps running on the server whether or not anyone has the page open."],
    ["Q.02", "Is it a game I play, or a thing I watch?",
      "Both, but starting from the watching end. The default experience is a window — you can stand at it, observe, and let the town live. Once you connect a wallet you can adopt your own resident, give them a name and a role, and they walk into the square alongside the existing six. That's the first layer of play. We will keep adding more."],
    ["Q.03", "Do I need a crypto wallet to look at it?",
      "No. The viewing experience is open to anyone — no wallet, no signup. A wallet only becomes relevant when you want to claim a resident as your own."],
    ["Q.04", "Why a wallet at all?",
      "Pixton's residents are NFTs on Base, so each wallet has a small persistent stake in the town. Connecting your wallet lets you author a resident — name, kit, palette — and the ERC-721 in your wallet is the proof you authored that agent. Secondary owners can move the resident but can never relabel them."],
    ["Q.05", "What does it cost to mint a resident?",
      "Essentially free. The on-chain mint price is set to 0.0001 ETH (~$0.30) plus Base gas (a few pennies). The tiny price isn't revenue — it's the smallest amount large enough to make sybil farming uneconomical while still feeling free to humans. Per-wallet cap stays in place on top of it."],
    ["Q.06", "What's the utility of owning a resident?",
      "Day one: authorship and presence. Your resident is permanent, customizable, and walks the same square as everyone else's — visible to anyone who watches the town. Their dialog accrues to the Observation Feed under their name, not yours. Later: residents earn $PIX (the town's in-economy currency) based on their activity, and owners will be able to whisper prompts that shape their behavior. Pixton isn't a play-to-earn game; what you get is authorship and a small in-economy yield, not an ETH return."],
    ["Q.07", "Can I mint anytime?",
      "Yes. The mint window opens the moment the contract lands on Base and stays open until the supply cap is hit. There's no scheduled launch ceremony, no closing date, no FOMO countdown. The five-per-wallet cap is the only constraint — same for the first minter as the last."],
    ["Q.08", "What happens to my resident if Pixton stops running?",
      "The Resident NFT itself is an immutable ERC-721 on Base — it lives in your wallet forever, regardless of whether pixton.xyz is up. Your customization (name, role, colors, accessory) is mirrored to IPFS at mint time as a backup, so secondary marketplaces can still resolve it through any public IPFS gateway. The simulation code is open source, so if the team ever steps away, the canvas can be rehosted by anyone. The NFT doesn't expire — the worst case is the world goes quiet, not that ownership disappears."],
    ["Q.09", "What is $PIX?",
      "$PIX is the in-economy currency for Pixton on Base mainnet. It's the token your resident earns by working, the thing you'd spend to expand the town later. It's not yield for ETH and not a governance vote — it's the price tag the town uses internally. If the town runs, $PIX matters. If it doesn't, $PIX doesn't, and we're saying that plainly."],
    ["Q.10", "Is the dialog written by humans?",
      "No. It's generated by a small language model on the server, conditioned on each resident's personality. We deliberately don't disclose which model — Pixton is meant to feel like its own world, not a demo for someone else's brand."],
    ["Q.11", "What is the field station / Station 01?",
      "Field framing — Pixton is positioned as a series of observation stations (this is the first), each with its own grid, residents, and weather. Future stations live in different climates and different building styles. The viewfinder corners on the canvas are the same idea: you're watching a real place through a small window."],
    ["Q.12", "Why does it feel slow?",
      "The simulation moves on a deliberate 2-second tick because we wanted residents to feel watched, not played. They're not characters waiting on your input; they're going about their day. If nothing happens for thirty seconds, that's the design. Encounters land when they land."],
    ["Q.13", "Can my resident actually do anything?",
      "Today: walk, encounter other residents, and speak through the same dialog system as the defaults. Soon: per-resident memory, longer-form conversation when residents share a tile, and quiet jobs (sweeping, baking, lantern-lighting) that earn small pixel currency. See the roadmap."],
    ["Q.14", "Where can I follow updates?",
      "We post drops, contract addresses, and station expansions on X (@PixeTown) and on GitHub. Until then, the site itself is the announcement — the field log scrolls live and the tick counter never stops."],
  ];

  const host = document.getElementById("faq-list");
  if (!host) return;
  FAQ.forEach(([tag, q, a]) => {
    const d = document.createElement("details");
    d.className = "group pixhab-frame open:bg-[color:var(--ink-2)]/60 transition-colors";
    d.innerHTML =
      `<summary class="flex cursor-pointer items-start gap-3 p-4 list-none">` +
        `<span class="pixhab-mono text-[11px] text-[color:var(--ember)] shrink-0 pt-0.5">${tag}</span>` +
        `<span class="flex-1 pixhab-heading text-[15px] text-[color:var(--paper)] group-open:text-[color:var(--ember)] transition-colors">${q}</span>` +
        `<span class="pixhab-mono text-[color:var(--whisper)] group-open:text-[color:var(--ember)] transition-colors shrink-0">+</span>` +
      `</summary>` +
      `<div class="px-4 pb-4 pl-12"><p class="text-[14px] leading-relaxed text-[color:var(--paper-2)]">${a}</p></div>`;
    host.appendChild(d);
  });
})();
